// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Include the trusted openenclavesample header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the openenclavesample.edl file.
#include "openenclavesample_t.h"

// This is the function that the host calls. It prints
// a message in the enclave before calling back out to
// the host to print a message from there too.
// void enclave_set_secret_value(char *buf, size_t len)
void enclave_set_secret_value(int *returnVal)
{

    int changeMe = 123456789;
    fprintf(stdout, "Value for changeMe (enclave): %d\n", changeMe);

    oe_result_t result = host_wait_key();
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "Call to host_wait_key failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
    }

    *returnVal = changeMe;
}
