#cloud-config
package_upgrade: true
packages:
  - [build-essential, 12.8ubuntu1]
  - [cmake, 3.16.3-1ubuntu1]
  - [git, 1:2.25.1-1ubuntu3]
  - [libcurl4-openssl-dev, 7.68.0-1ubuntu2]
  - [libjsoncpp-dev, 1.7.4-3.1ubuntu2]
runcmd:
  - git clone https://github.com/ThomVanL/confidential-computing-cvm-guest-attestation.git
  - wget https://packages.microsoft.com/repos/azurecore/pool/main/a/azguestattestation1/azguestattestation1_1.0.2_amd64.deb --directory-prefix=/opt
  - dpkg -i /opt/azguestattestation1_1.0.2_amd64.deb