#cloud-config
package_upgrade: true
packages:
  - [build-essential, 12.8ubuntu1]
  - [cmake, 3.16.3-1ubuntu1]
  - [git, 1:2.25.1-1ubuntu3]
runcmd:
  - apt-get -y install linux-headers-$(uname -r)
  - git clone https://github.com/ThomVanL/session-2022-exploring-azure-confidential-computing.git